"""Add users table

Revision ID: 2b7526941839
Revises: 
Create Date: 2022-09-05 22:29:30.350627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7526941839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='template'
    )
    op.create_index(op.f('ix_template_users_email'), 'users', ['email'], unique=True, schema='template')
    op.create_index(op.f('ix_template_users_id'), 'users', ['id'], unique=False, schema='template')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_users_id'), table_name='users', schema='template')
    op.drop_index(op.f('ix_template_users_email'), table_name='users', schema='template')
    op.drop_table('users', schema='template')
    # ### end Alembic commands ###
