# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x64\x65\x66inition.proto"\x07\n\x05\x45mpty";\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x17\n\x0fhashed_password\x18\x02 \x01(\t"%\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t2;\n\x0b\x44\x65\x66initions\x12,\n\x0b\x63reate_user\x12\x12.CreateUserRequest\x1a\t.UserDatab\x06proto3'
)


_EMPTY = DESCRIPTOR.message_types_by_name["Empty"]
_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name["CreateUserRequest"]
_USERDATA = DESCRIPTOR.message_types_by_name["UserData"]
Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "definition_pb2"
        # @@protoc_insertion_point(class_scope:Empty)
    },
)
_sym_db.RegisterMessage(Empty)

CreateUserRequest = _reflection.GeneratedProtocolMessageType(
    "CreateUserRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CREATEUSERREQUEST,
        "__module__": "definition_pb2"
        # @@protoc_insertion_point(class_scope:CreateUserRequest)
    },
)
_sym_db.RegisterMessage(CreateUserRequest)

UserData = _reflection.GeneratedProtocolMessageType(
    "UserData",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERDATA,
        "__module__": "definition_pb2"
        # @@protoc_insertion_point(class_scope:UserData)
    },
)
_sym_db.RegisterMessage(UserData)

_DEFINITIONS = DESCRIPTOR.services_by_name["Definitions"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _EMPTY._serialized_start = 20
    _EMPTY._serialized_end = 27
    _CREATEUSERREQUEST._serialized_start = 29
    _CREATEUSERREQUEST._serialized_end = 88
    _USERDATA._serialized_start = 90
    _USERDATA._serialized_end = 127
    _DEFINITIONS._serialized_start = 129
    _DEFINITIONS._serialized_end = 188
# @@protoc_insertion_point(module_scope)
